Repository exomatics/Darkify, pull requests merged in 2024-12, with the labels that each got.

#2 rebase to esm and typescript fixes and continuous integration
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
  .github/workflows/ts.yml
  backend/api.md
  backend/eslint.config.mjs
  backend/models/playlistTracksModel.ts
  backend/models/trackModel.ts
  backend/models/userFollowersModel.ts
  backend/models/userFollowingModel.ts
  backend/models/userModel.ts
  backend/package-lock.json
  backend/package.json
  backend/prettier.config.js
  backend/settings.json
  backend/src/app.ts
  backend/src/config/db.sql
  backend/src/config/db.ts
  backend/src/controllers/authController.ts
  backend/src/controllers/playlistController.ts
  backend/src/controllers/trackController.ts
  backend/src/controllers/userController.ts
  backend/src/interfaces/dbInterface.ts
  backend/src/interfaces/playlistInterface.ts
  backend/src/interfaces/trackInterface.ts
  backend/src/interfaces/userInterface.ts
  backend/src/middleware/authMiddleware.ts
  backend/src/models/playlistModel.ts
  backend/src/models/playlistTracksModel.ts
  backend/src/models/trackModel.ts
  backend/src/models/userFollowersModel.ts
  backend/src/models/userFollowingModel.ts
  backend/src/models/userModel.ts
  backend/src/routes/authRoute.ts
  backend/src/routes/playlistRoute.ts
  backend/src/routes/routes.ts
  backend/src/routes/trackRoute.ts
  backend/src/routes/userRoute.ts
  backend/src/server.ts
  backend/tsconfig.json
  backend/urlRequests.ts
  web/eslint.config.js
  web/package.json
  web/prettier.config.cjs
  web/settings.json
  web/src/App.tsx
  web/src/main.tsx
  web/tsconfig.json
Labels: backend, cicd

#4 docker deployment
  backend/Dockerfile
  backend/docker-compose.yml
  backend/package.json
Labels: cicd

#14 feat(auth): implement JWT authorization
  backend/.gitignore
  backend/eslint.config.mjs
  backend/package-lock.json
  backend/package.json
  backend/settings.json
  backend/src/app.ts
  backend/src/config/authentication.ts
  backend/src/config/config.ts
  backend/src/config/create-key-pair.ts
  backend/src/config/database.ts
  backend/src/config/logger.ts
  backend/src/controllers/auth-controller.ts
  backend/src/controllers/track-controller.ts
  backend/src/controllers/user-controller.ts
  backend/src/interfaces/database-interface.ts
  backend/src/interfaces/playlist-interface.ts
  backend/src/interfaces/track-interface.ts
  backend/src/interfaces/user-interface.ts
  backend/src/models/playlist-model.ts
  backend/src/models/playlist-tracks-model.ts
  backend/src/models/track-model.ts
  backend/src/models/user-followers-model.ts
  backend/src/models/user-following-model.ts
  backend/src/models/user-model.ts
  backend/src/routes/auth-route.ts
  backend/src/routes/routes.ts
  backend/src/routes/track-route.ts
  backend/src/routes/user-route.ts
  backend/src/utils/jwt-issuance.ts
  backend/src/utils/password-generation.ts
  backend/src/utils/password-verification.ts
  backend/tsconfig.json
Labels: feature, backend

#20 chore: add editor config
  backend/.editorconfig
  web/.editorconfig
Labels: chore

#19 chore: add LICENSE and package.json fixes
  backend/LICENSE
  backend/package.json
  web/LICENSE
  web/package.json
Labels: chore
